### ISSUE TITLE
Azure Translator Service Keys are not working within the tool

### ISSUE THREAD

**Issue by mugedegerliyurt** [MicrosoftTranslator/DocumentTranslation#108]
Hello, I tried to use DocumentTranslator setup with my existing Azure translator service credentials on Windows machine - I installed successfully the tool but having problem with testing and saving my credential details under settings. I tried to connect and call the service with postman using same keys and region in addition to endpoints and it is working fine, but with the tool I am getting  ''invalid key, or key does not match region'' error. Could you please help me to understand what I am missing? Thank you!

**Comment by mugedegerliyurt** [comment]
Hi Chris, Thank you so mych for the response. Sorry I didn’t put so much details as you mentioned. Yes mine is the same as like yours, I provided all the details. I am using Key1- westeurope- text translation endpoint- document translation endpoint(in my case they are the same with text translation endpoint) - and storage connection string. I shouldn’t use any prefix or nothing in adresses I assume? I will try again by checking yours but to be honest I am getting this error for each try. Thank you, Best!Müge10.01.2023, 16:58, "Chris Wendt" ***@***.***>:
Hi Müge,
From your report is not clear to me whether you tried document translation or simple text translation using postman. The requirements for document translation are more extensive.
Please check if your settings are complete and matching. Here are mine:

As region, you need to use the short form of the region, like "eastus2" in my case.

**Comment by chriswendt1** [comment]
Hi Müge,

The text translation and document translation endpoints cannot be the same. Text translation endpoint is fixed by Microsoft, document translation endpoint is personal to your resource.
You copy the endpoints exactly as they are listed in the Azure portal, under your Translator resource. No modification. 

![image](https://user-images.githubusercontent.com/11096941/211616855-0ab7516e-8def-4949-b1e3-33e4dfc3d197.png)

**Comment by mugedegerliyurt** [comment]
Dear Chris,

Yes - even  updated the document translation and text translation endpoints as shown (I copied them from the Azure Portal) still having the same error. For westeurope region there is no shortcut availability as far as I know. Do you have any idea on that?

![Capture](https://user-images.githubusercontent.com/5527165/211771010-4a1c69e6-afe9-40f7-bd7a-3f9320bfda04.PNG)

**Comment by mugedegerliyurt** [comment]
Ah I tried another setting - since but I got another error - it seems I have subscription problem. I will try on to solve it. Thank you so much for your support. 
![Capture](https://user-images.githubusercontent.com/5527165/211772197-b1245936-dd83-4905-951b-b6001e65deeb.PNG)

**Comment by mugedegerliyurt** [comment]
Hi Chris,
I checked it and my translator service links to Sandbox subscription within the free tier. I think it's the case. I will try to test with S1 subsc. then will update the thread. Thank you a lot for your support.

**Comment by chriswendt1** [comment]
Document Translation is not available in a free subscription. Requires S1 minimum. I will check on the error message.

**Comment by mugedegerliyurt** [comment]
I could run the tool successfully, thank you Chris! I have another question - if I wanna implement another UI for the tool - for compiling in my local environment is there any special nugget or env. extensions that I need to be careful? Thank you a lot for your help.

**Comment by chriswendt1** [comment]
The VS project should pull in all required Nugets automatically. If you are using the latest production Visual Studio 2022, it should be smooth.
The Github project pulls in another project, `DocumentTranslationService`. The project links to a specific version of it and I am not always sure the versioned link pulls in the current version of `DocumentTranslationService`. Best to use the current version of `DocumentTranslationService`.
Please share your UI improvements back.

**Comment by chriswendt1** [comment]
Please copy the text translation endpoint from the Azure portal exactly, without modifications.
Yours doesn't look right:
![image](https://user-images.githubusercontent.com/11096941/211881595-034f49e4-45a7-406a-a556-a0e97eeaa68e.png)

**Comment by mugedegerliyurt** [comment]
Hi Chris,
Yes when I realized it yesterday I changed and fixed the connection problem. It is working well - that's why I closed the issue. Thank you so much for your support. For your previous note- of course I will share the improvements. Thank you for the clarification.

**Comment by mugedegerliyurt** [comment]
Hi Chris, I am trying to open the project in VS 2022 professional; having this error on DocumentTranslationService - as we talked about it before how I can customize the version of service since I am using the project directly. Thank you, Best!Muge 11.01.2023, 19:12, "Chris Wendt" ***@***.***>: The VS project should pull in all required Nugets automatically. If you are using the latest production Visual Studio 2022, it should be smooth.The Github project pulls in another project, DocumentTranslationService. The project links to a specific version of it and I am not always sure the versioned link pulls in the current version of DocumentTranslationService. Best to use the current version of DocumentTranslationService.Please share your UI improvements back.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by mugedegerliyurt** [comment]
Sorry forgot to paste error: UnsupportedThis version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them.For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.     - DocumentTranslation.Setup, "C:\Users\ozkan\Desktop\DocumentTranslation-master\DocumentTranslation.Setup\DocumentTranslation.Setup.wixproj" No changes requiredThese projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.     - doctr, "C:\Users\ozkan\Desktop\DocumentTranslation-master\DocumentTranslation.CLI\doctr.csproj"     - Solution Items, "Solution Items"     - DocumentTranslation.GUI, "C:\Users\ozkan\Desktop\DocumentTranslation-master\DocumentTranslation.GUI\DocumentTranslation.GUI.csproj"     - docs, "docs"     - images, "images"     - DocumentTranslationService, "C:\Users\ozkan\Desktop\DocumentTranslationService\DocumentTranslationService.csproj"     - DocumentTranslation, "C:\Users\ozkan\Desktop\DocumentTranslation-master\DocumentTranslation.sln" 13.02.2023, 15:27, "Özkan Müge" ***@***.***>:Hi Chris, I am trying to open the project in VS 2022 professional; having this error on DocumentTranslationService - as we talked about it before how I can customize the version of service since I am using the project directly. Thank you, Best!Muge 11.01.2023, 19:12, "Chris Wendt" ***@***.***>: The VS project should pull in all required Nugets automatically. If you are using the latest production Visual Studio 2022, it should be smooth.The Github project pulls in another project, DocumentTranslationService. The project links to a specific version of it and I am not always sure the versioned link pulls in the current version of DocumentTranslationService. Best to use the current version of DocumentTranslationService.Please share your UI improvements back.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by chriswendt1** [comment]
Hi Müge,
The setup project uses the Wix Installer.
Install from: https://wixtoolset.org/

**Comment by mugedegerliyurt** [comment]
Hi Chris, Thank you so much even though I installed and integrated Wix to VS - then cloned the git project:having this error :( (attached) Actually, my aim was to do UI enhancements and some other customizations for my environment but I couldn't run the project properly.Do you have any idea? - btw if I open the DocumentTranslationService project all is good - if I open the DocumentTranslation one then I am getting these errors. Thank you so much, Kind Regards!M   13.02.2023, 21:51, "Chris Wendt" ***@***.***>: Hi Müge,The setup project uses the Wix Installer.Install from: https://wixtoolset.org/—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by chriswendt1** [comment]
Ah, OK.
Do you actually have content in you DocumentTranslationService project location? If not, clone it from https://github.com/MicrosoftTranslator/DocumentTranslationService in the expected location.

**Comment by mugedegerliyurt** [comment]
Yes I do have it - I am able to open DocumentTranslationService.sln separately and properly but when I am trying to open the DocumentTranslation.sln then I am getting error for service one.That's why it's weird :( Thank you,M 14.02.2023, 18:37, "Chris Wendt" ***@***.***>: Ah, OK.Do you actually have content in you DocumentTranslationService project location? If not, clone it from https://github.com/MicrosoftTranslator/DocumentTranslationService in the expected location.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by chriswendt1** [comment]
Is the DocumentTranslationService in the correct location? It needs to be under DocumentTranslation.
![image](https://user-images.githubusercontent.com/11096941/218799978-1d376f5b-ffee-4ecd-8d8c-de04b293b957.png)

**Comment by chriswendt1** [comment]
Or you can delete the DocumentTranslationService project from the solution and add it back in the correct location.

**Comment by mugedegerliyurt** [comment]
Yes, the folder path is the same as you sent me.I really couldn't solve what is the issue by not opening the project since individually DocumentTranslationService is able to open. Thank you,M 14.02.2023, 19:37, "Chris Wendt" ***@***.***>: Is the DocumentTranslationService in the correct location? It needs to be under DocumentTranslation.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by chriswendt1** [comment]
Try deleting the DocumentTranslationService project and then add it back.

**Comment by mugedegerliyurt** [comment]
Unfortunately I even tried to change the folder path within the project but it is not working. Any other idea?I am directly cloning the project actually. 15.02.2023, 18:32, "Chris Wendt" ***@***.***>: Try deleting the DocumentTranslationService project and then add it back.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by mugedegerliyurt** [comment]
I fixed the issue. 16.02.2023, 12:54, "Özkan Müge" ***@***.***>:Unfortunately I even tried to change the folder path within the project but it is not working. Any other idea?I am directly cloning the project actually. 15.02.2023, 18:32, "Chris Wendt" ***@***.***>: Try deleting the DocumentTranslationService project and then add it back.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by chriswendt1** [comment]
Great! What was the underlying problem and how did you fix it?
